---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: k8s-utils
  labels:
    app: k8s-utils
    tier: proxy
    component: nginx
data:
  nginx.conf: |
    # needed to avoid crashing
    events {}

    http {
      upstream backend {
        server "go:80";
      }

      upstream frontend {
        server react:3000;
      }

      server {
        listen 8080;
        location / {
          proxy_pass http://frontend/;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
        }
        location /api/ {
          proxy_pass http://go/api/;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
