---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: k8s-utils
  labels:
    app: k8s-utils
    tier: proxy
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-utils
      tier: proxy
      component: nginx
  template:
    metadata:
      labels:
        app: k8s-utils
        tier: proxy
        component: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 4443
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: config
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 10000
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx
        name: config