---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: k8s-utils
  labels:
    app: k8s-utils
    tier: proxy
    component: nginx
spec:
  type: NodePort
  selector:
    app: k8s-utils
    tier: proxy
    component: nginx
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32700
    port: 80
    protocol: TCP
    targetPort: 8080
