---
apiVersion: rbac.authorization.k8s.io/v1
kind: Clusterrole
metadata:
  name: go
  labels: 
    tier: backend
    language: golang
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/log
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - watch
  - list
  - create
  - update
