---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-pod-manager
subjects:
- kind: ServiceAccount
  name: go
roleRef:
  kind: ClusterRole
  name: go
  apiGroup: rbac.authorization.k8s.io
