---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  namespace: k8s-utils
  labels:
    tier: backend
    language: golang
spec:
  replicas: 1
  selector: 
    matchLabels: 
      tier: backend
      language: golang
  template: 
    metadata: 
      labels: 
        tier: backend
        language: golang
    spec: 
      containers: 
      - name: go
        image: docker.registry.pr.ch/golang-backend:1.0.0
        imagePullPolicy: IfNotPresent
        resources: {}
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /root/.kube
      volumes:
      - name: config
        configMap:
          name: kubeconfig
      restartPolicy: Always
