---
apiVersion: v1
kind: Service
metadata:
  name: go
  namespace: k8s-utils
  labels:
    tier: backend
    language: golang
spec:
  selector:
    tier: backend
    language: golang  
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP