---
apiVersion: v1
kind: Service
metadata:
  name: go
  labels:
    tier: backend
    language: golang
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP